version: '3'
services:
  db:
    build:
      context: .  # This specifies the build context
      dockerfile: dockerfile.db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"




